// Sample profiles data
export const profiles = [
  {
    name: "Jack",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "50",
    id: "a35042b4-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "John",
    age: "9",
    parents: "Mr. and Mrs. Stapleton",
    progress: "25",
    id: "bb2d6bc8-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Marily",
    age: "9",
    parents: "Mr. and Mrs. Weasley",
    progress: "75",
    id: "c20f5d3e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Katlyn",
    age: "9",
    parents: "Mr. and Mrs. Eberley",
    progress: "20",
    id: "c7ac20f6-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Tiffany",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "100",
    id: "cd747c0e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Katlyn",
    age: "9",
    parents: "Mr. and Mrs. Eberley",
    progress: "20",
    id: "c7ac20f6-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Katlyn",
    age: "9",
    parents: "Mr. and Mrs. Eberley",
    progress: "20",
    id: "c7ac20f6-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Katlyn",
    age: "9",
    parents: "Mr. and Mrs. Eberley",
    progress: "20",
    id: "c7ac20f6-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Tiffany",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "100",
    id: "cd747c0e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Tiffany",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "100",
    id: "cd747c0e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Tiffany",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "100",
    id: "cd747c0e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
  {
    name: "Tiffany",
    age: "9",
    parents: "Mr. and Mrs. Johnson",
    progress: "100",
    id: "cd747c0e-7d5c-11ee-b962-0242ac120002",
    difficulties: [
      "Difficulty Making Inferences",
      "Poor Recall",
      "Trouble with Summarization",
    ],
  },
];
